#!/usr/bin/zsh

# Set the hostname Windows-style.

OLDHOSTNAME=$(hostname)
HOSTNAME="Desktop-$(head -n3 /dev/urandom | tr -cd '0-9A-Z' | cut -c -7)"
hostname $HOSTNAME

echo "Set hostname: $HOSTNAME (Old hostname: $OLDHOSTNAME)"
